version: "3.8"

services:
  calendar-sync:
    build: .
    image: calendar-sync:latest
    container_name: calendar-sync-service
    restart: unless-stopped
    
    # Environment configuration
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    
    # Security: run as non-root user
    user: "1001:1001"
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check'); process.exit(0)"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3
    
    # Volumes for persistent data (optional)
    # volumes:
    #   - ./logs:/app/logs
    #   - ./data:/app/data
    
    # Network configuration (if needed)
    # networks:
    #   - calendar-sync-network

# Optional: Custom network
# networks:
#   calendar-sync-network:
#     driver: bridge
